-- ESQUEMA SQL PARA SUPABASE - COFERSA NE
-- Este script crea las tablas necesarias para Lovable + Supabase

-- 1. TIPOS ENUMERADOS (Para asegurar integridad)
CREATE TYPE user_role AS ENUM ('vendedor', 'supervisor', 'gerente_ventas', 'compras', 'admin');
CREATE TYPE request_status AS ENUM ('borrador', 'pendiente', 'en_revision', 'escalada', 'aprobada', 'parcialmente_aprobada', 'rechazada', 'cancelada');
CREATE TYPE sku_status AS ENUM ('pendiente', 'aprobado', 'rechazado');

-- 2. TABLA DE PERFILES (Extiende la tabla auth.users de Supabase)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  email TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'vendedor',
  supervisor_id UUID REFERENCES profiles(id),
  status TEXT DEFAULT 'activo',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. REGLAS DE APROBACIÓN POR MARCA
CREATE TABLE reglas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marca TEXT UNIQUE NOT NULL,
  clasificacion TEXT,
  limite_vendedor NUMERIC NOT NULL DEFAULT 0,
  limite_supervisor NUMERIC NOT NULL,
  limite_gte_ventas NUMERIC NOT NULL DEFAULT 0,
  limite_compras NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. PRESUPUESTO MENSUAL
CREATE TABLE presupuesto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supervisor_username TEXT NOT NULL,
  asesor_username TEXT NOT NULL,
  marca TEXT NOT NULL,
  ppto_mensual_crc NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SOLICITUDES DE NEGOCIACIÓN
CREATE TABLE solicitudes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio TEXT UNIQUE,
  cliente_codigo TEXT NOT NULL,
  cliente_nombre TEXT NOT NULL,
  numero_pedido TEXT,
  justificacion TEXT NOT NULL,
  estado request_status DEFAULT 'pendiente',
  vendedor_id UUID REFERENCES profiles(id) NOT NULL,
  aprobador_actual_id UUID REFERENCES profiles(id),
  aprobador_nivel TEXT,
  aprobador_final_id UUID REFERENCES profiles(id),
  comentario_aprobador TEXT,
  monto_total_descuento NUMERIC DEFAULT 0,
  monto_total_aprobado NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  sla_deadline TIMESTAMPTZ
);

-- 6. DETALLE DE SKUS (Líneas de la solicitud)
CREATE TABLE solicitud_skus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solicitud_id BIGINT REFERENCES solicitudes(id) ON DELETE CASCADE NOT NULL,
  marca TEXT NOT NULL,
  clasificacion TEXT,
  codigo_sku TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  bdf TEXT,
  cantidad NUMERIC NOT NULL DEFAULT 1,
  precio_base NUMERIC NOT NULL,
  porcentaje_descuento_sol NUMERIC NOT NULL,
  precio_solicitado NUMERIC NOT NULL,
  monto_descuento NUMERIC NOT NULL,
  porcentaje_aprobado NUMERIC,
  precio_aprobado NUMERIC,
  monto_aprobado NUMERIC,
  sku_estado sku_status DEFAULT 'pendiente',
  sku_comentario TEXT,
  aprobado_por UUID REFERENCES profiles(id),
  aprobado_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. AUDITORÍA
CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  username TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. SEGURIDAD (Row Level Security - RLS)
-- Habilitar RLS en todas las tablas
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reglas ENABLE ROW LEVEL SECURITY;
ALTER TABLE presupuesto ENABLE ROW LEVEL SECURITY;
ALTER TABLE solicitudes ENABLE ROW LEVEL SECURITY;
ALTER TABLE solicitud_skus ENABLE ROW LEVEL SECURITY;

-- Ejemplo de política: Todos los usuarios autenticados pueden leer reglas
CREATE POLICY "Lectura de reglas para usuarios autenticados" ON reglas
  FOR SELECT USING (auth.role() = 'authenticated');

-- Ejemplo de política: Los vendedores solo ven sus propias solicitudes
CREATE POLICY "Vendedores ven sus propias solicitudes" ON solicitudes
  FOR SELECT USING (
    auth.uid() = vendedor_id OR
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'compras', 'gerente_ventas'))
  );

-- 9. FUNCIONES AUTOMÁTICAS
-- Función para actualizar el campo updated_at automáticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_solicitudes_updated_at BEFORE UPDATE ON solicitudes FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_reglas_updated_at BEFORE UPDATE ON reglas FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_presupuesto_updated_at BEFORE UPDATE ON presupuesto FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
